workflows:
  react-native-android:
    name: React Native Android Workflow
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.sqa.earnigs" # আপনার app package
      node: 16
      java: 11
      android: true
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - bdsonghd3@gmail.com

